version: '3'

services:
  nestjs-app:
    image: nestjs-image
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    # volumes:
    #   - ./server:/app

  angular-app:
    image: angular-image
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - nestjs-app